#%RAML 1.0
title: placeholder
version: 1.0
/1:
  get:
/4:
  get:
/6: 
  get:
/7: 
  get:
/9: 
  post:
/11: 
  get:
/13: 
  get:
/14: 
  get:
/20:
  get: 
/24:
  get:
/child:
  post:
/26:
  get:
/30:
  get:
/49:
  get:
/76:
  get:
/85:
 get:
/87:
 get:
/89:
 get: